"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from supertone.errors import SupertoneError
from supertone.models import badrequesterrorresponse as models_badrequesterrorresponse
from supertone.types import BaseModel
from typing import Optional


class BadRequestErrorResponseData(BaseModel):
    status: str
    r"""Response status"""

    message: models_badrequesterrorresponse.BadRequestErrorResponseMessage
    r"""Bad request error details"""


class BadRequestErrorResponse(SupertoneError):
    data: BadRequestErrorResponseData

    def __init__(
        self,
        data: BadRequestErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
