"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from supertone.errors import SupertoneError
from supertone.models import forbiddenerrorresponse as models_forbiddenerrorresponse
from supertone.types import BaseModel
from typing import Optional


class ForbiddenErrorResponseData(BaseModel):
    status: str
    r"""Response status"""

    message: models_forbiddenerrorresponse.ForbiddenErrorResponseMessage
    r"""Forbidden error details"""


class ForbiddenErrorResponse(SupertoneError):
    data: ForbiddenErrorResponseData

    def __init__(
        self,
        data: ForbiddenErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
