"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from supertone.errors import SupertoneError
from supertone.models import (
    internalservererrorresponse as models_internalservererrorresponse,
)
from supertone.types import BaseModel
from typing import Optional


class InternalServerErrorResponseData(BaseModel):
    status: str
    r"""Response status"""

    message: models_internalservererrorresponse.InternalServerErrorResponseMessage
    r"""Internal server error details"""


class InternalServerErrorResponse(SupertoneError):
    data: InternalServerErrorResponseData

    def __init__(
        self,
        data: InternalServerErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
