"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from supertone.errors import SupertoneError
from supertone.models import notfounderrorresponse as models_notfounderrorresponse
from supertone.types import BaseModel
from typing import Optional


class NotFoundErrorResponseData(BaseModel):
    status: str
    r"""Response status"""

    message: models_notfounderrorresponse.NotFoundErrorResponseMessage
    r"""Not found error details"""


class NotFoundErrorResponse(SupertoneError):
    data: NotFoundErrorResponseData

    def __init__(
        self,
        data: NotFoundErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
