"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from supertone.errors import SupertoneError
from supertone.models import (
    payloadtoolargeerrorresponse as models_payloadtoolargeerrorresponse,
)
from supertone.types import BaseModel
from typing import Optional


class PayloadTooLargeErrorResponseData(BaseModel):
    status: str
    r"""Response status"""

    message: models_payloadtoolargeerrorresponse.PayloadTooLargeErrorResponseMessage
    r"""Payload too large error details"""


class PayloadTooLargeErrorResponse(SupertoneError):
    data: PayloadTooLargeErrorResponseData

    def __init__(
        self,
        data: PayloadTooLargeErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
