"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from supertone.errors import SupertoneError
from supertone.models import (
    paymentrequirederrorresponse as models_paymentrequirederrorresponse,
)
from supertone.types import BaseModel
from typing import Optional


class PaymentRequiredErrorResponseData(BaseModel):
    status: str
    r"""Response status"""

    message: models_paymentrequirederrorresponse.PaymentRequiredErrorResponseMessage
    r"""Payment required error details"""


class PaymentRequiredErrorResponse(SupertoneError):
    data: PaymentRequiredErrorResponseData

    def __init__(
        self,
        data: PaymentRequiredErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
