"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from supertone.errors import SupertoneError
from supertone.models import (
    requesttimeouterrorresponse as models_requesttimeouterrorresponse,
)
from supertone.types import BaseModel
from typing import Optional


class RequestTimeoutErrorResponseData(BaseModel):
    status: str
    r"""Response status"""

    message: models_requesttimeouterrorresponse.RequestTimeoutErrorResponseMessage
    r"""Request timeout error details"""


class RequestTimeoutErrorResponse(SupertoneError):
    data: RequestTimeoutErrorResponseData

    def __init__(
        self,
        data: RequestTimeoutErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
