"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from supertone.errors import SupertoneError
from supertone.models import (
    unauthorizederrorresponse as models_unauthorizederrorresponse,
)
from supertone.types import BaseModel
from typing import Optional


class UnauthorizedErrorResponseData(BaseModel):
    status: str
    r"""Response status"""

    message: models_unauthorizederrorresponse.UnauthorizedErrorResponseMessage
    r"""Unauthorized error details"""


class UnauthorizedErrorResponse(SupertoneError):
    data: UnauthorizedErrorResponseData

    def __init__(
        self,
        data: UnauthorizedErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
