"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from supertone.errors import SupertoneError
from supertone.models import (
    unsupportedmediatypeerrorresponse as models_unsupportedmediatypeerrorresponse,
)
from supertone.types import BaseModel
from typing import Optional


class UnsupportedMediaTypeErrorResponseData(BaseModel):
    status: str
    r"""Response status"""

    message: models_unsupportedmediatypeerrorresponse.UnsupportedMediaTypeErrorResponseMessage
    r"""Unsupported media type error details"""


class UnsupportedMediaTypeErrorResponse(SupertoneError):
    data: UnsupportedMediaTypeErrorResponseData

    def __init__(
        self,
        data: UnsupportedMediaTypeErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
