"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updatecustomvoicerequest import (
    UpdateCustomVoiceRequest,
    UpdateCustomVoiceRequestTypedDict,
)
from supertone.types import BaseModel
from supertone.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class EditCustomVoiceRequestTypedDict(TypedDict):
    voice_id: str
    update_custom_voice_request: UpdateCustomVoiceRequestTypedDict


class EditCustomVoiceRequest(BaseModel):
    voice_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    update_custom_voice_request: Annotated[
        UpdateCustomVoiceRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
