"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .getcustomvoiceresponse import (
    GetCustomVoiceResponse,
    GetCustomVoiceResponseTypedDict,
)
from pydantic import model_serializer
from supertone.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import List
from typing_extensions import NotRequired, TypedDict


class GetCustomVoiceListResponseTypedDict(TypedDict):
    items: List[GetCustomVoiceResponseTypedDict]
    r"""List of custom voice items"""
    total: float
    r"""Total number of available custom voices"""
    next_page_token: NotRequired[Nullable[str]]
    r"""Token for fetching the next page of results. A valid non-negative integer string (e.g., \"10\", \"20\"). Null if no more pages."""


class GetCustomVoiceListResponse(BaseModel):
    items: List[GetCustomVoiceResponse]
    r"""List of custom voice items"""

    total: float
    r"""Total number of available custom voices"""

    next_page_token: OptionalNullable[str] = UNSET
    r"""Token for fetching the next page of results. A valid non-negative integer string (e.g., \"10\", \"20\"). Null if no more pages."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["next_page_token"]
        nullable_fields = ["next_page_token"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
