"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apisampledata import APISampleData, APISampleDataTypedDict
from pydantic import model_serializer
from supertone.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class GetCharacterByIDResponseTypedDict(TypedDict):
    voice_id: str
    r"""Unique identifier for the voice"""
    name: str
    r"""Name of the voice"""
    age: str
    r"""Age of the voice"""
    gender: str
    r"""Gender of the voice"""
    use_case: str
    r"""Use case of the voice"""
    use_cases: List[str]
    r"""Use cases of the voice (array)"""
    language: List[str]
    r"""Languages supported by the voice"""
    styles: List[str]
    r"""Styles available for the voice"""
    models: List[str]
    r"""Models available for the voice"""
    description: NotRequired[Nullable[str]]
    r"""Description of the voice"""
    samples: NotRequired[List[APISampleDataTypedDict]]
    r"""URL to the sample audio file for the voice"""
    thumbnail_image_url: NotRequired[str]
    r"""URL to the thumbnail image for the voice"""


class GetCharacterByIDResponse(BaseModel):
    voice_id: str
    r"""Unique identifier for the voice"""

    name: str
    r"""Name of the voice"""

    age: str
    r"""Age of the voice"""

    gender: str
    r"""Gender of the voice"""

    use_case: str
    r"""Use case of the voice"""

    use_cases: List[str]
    r"""Use cases of the voice (array)"""

    language: List[str]
    r"""Languages supported by the voice"""

    styles: List[str]
    r"""Styles available for the voice"""

    models: List[str]
    r"""Models available for the voice"""

    description: OptionalNullable[str] = UNSET
    r"""Description of the voice"""

    samples: Optional[List[APISampleData]] = None
    r"""URL to the sample audio file for the voice"""

    thumbnail_image_url: Optional[str] = None
    r"""URL to the thumbnail image for the voice"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["description", "samples", "thumbnail_image_url"]
        nullable_fields = ["description"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
