"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from supertone.types import BaseModel
from typing_extensions import TypedDict


class GetCustomVoiceResponseDataTypedDict(TypedDict):
    voice_id: str
    r"""Unique identifier for the custom voice"""
    name: str
    r"""Name of the custom voice"""
    description: str
    r"""Description of the custom voice"""


class GetCustomVoiceResponseData(BaseModel):
    voice_id: str
    r"""Unique identifier for the custom voice"""

    name: str
    r"""Name of the custom voice"""

    description: str
    r"""Description of the custom voice"""
